branches:
  only:
  - master
before_install:
#- git rm --cached pelican-plugins
- git submodule add -f https://github.com/getpelican/pelican-plugins.git
- git submodule add -f https://github.com/molivier/nest.git pelican-themes/nest
#- git submodule update --init --recursive
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
#    pandoc_version: 1.17.0.3
language: python
cache: packages
r_packages:
- knitr
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
after_success: bash deploy.sh
env:
  global:
    secure: VkoNuUnYlyNfBLb+DKN1R/HFao9Gq9z3RA0CWX/dUnLgGFldR9j7BrkSJGndBmJNKttia6QyFy3HNDMwU84VCik+l/6iba1cZmTm+O/5fgycnEK0m42dRQWPZtDumeEWRhKLYSormvqctMl17i2ggCa/X1DcP0aUxmmbosym47UYpy64N2ycDgr/sot77CBUGMYbNja+2INgyWpuaelSAUP3JiRVxMYHAoyCKr8QtBZ4nrQSQG+ygJoM6YWnSzO3Dr49qEvnxkEUTUiOuhoz57ob/M6Gp/oKnNoouDa/WYWqS/+9p+GtUC5zZibNX9w0rmw3/TW3Ypb2Fdfb5yz5I+y2GSnz+WwMXSQBDv4O43ZC0onSGP04SJ6aXD6A1MeU8QhCJoLgOp+P4OLHFAkQzASdVHCnxsaVjB4K9vrWrzBAW0asxuYe5wYBSZb8JMpkOIvy1FrE4oYiBqBsXdhLmyLKPklYWmDUaA8wbOCSUL+fOWNzmPkZbrpthhqGrBX4Ig2qxeFYXUqe712uTyaZgUQjodXGOd9iyt3lQGhb+tWVSfKA/H1+52wmllc+1R7h2v9fbNJ4HVCnlue/V7RVNAPGZZ9CiQ6mSkEFE4QEu7qY5LK7yjG07O7wcDzEA26DEfY/tKSVtri1qTzgYMVUtOXLxLsmCUdSuAfLmBEW6C8=
